-- Tabela plano_de_contas

insert into plano_de_contas(nome, natureza) values
('CAIXA E EQUIVALENTES DE CAIXA', 'D'),
('BANCOS CONTA MOVIMENTO', 'D'),
('APLICACOES FINANCEIRAS DE LIQUIDEZ IMEDIATA', 'D'),
('CRÉDITOS A CURTO PRAZO', 'D'),
('CLIENTES (DUPLICATAS A RECEBER)', 'D'),
('EMPRÉSTIMOS E FINANCIAMENTOS CONCEDIDOS', 'D'),
('AJUSTE DE PERDAS DE CRÉDITOS A CURTO PRAZO', 'C'),
('ENCARGOS FINANCEIROS (ATIVOS) A APROPRIAR/A VENCER/A TRANSCORRER', 'C'),
('DEMAIS CRÉDITOS E VALORES A CURTO PRAZO', 'D'),
('ADIANTAMENTOS CONCEDIDOS A PESSOAL E A TERCEIROS', 'D'),
('TRIBUTOS A RECUPERAR/COMPENSAR', 'D'),
('IPI A RECUPERAR/COMPENSAR', 'D'),
('ICMS A RECUPERAR/COMPENSAR', 'D'),
('IR E CSLL A RECUPERAR/COMPENSAR', 'D'),
('OUTROS TRIBUTOS A RECUPERAR/COMPENSAR', 'D'),
('ICMS DIFERIDO', 'D'),
('IR E CSLL DIFERIDOS', 'D'),
('OUTROS CRÉDITOS A RECEBER E VALORES A CURTO PRAZO ', 'D'),
('ALUGUÉIS A RECEBER', 'D'),
('DIVIDENDOS PROPOSTOS A RECEBER', 'D'),
('REMUNERAÇÃO DE DEBÊNTURES A RECEBER', 'D'),
('TÍTULOS A RECEBER', 'D'),
('OUTROS CRÉDITOS A RECEBER E VALORES DE CURTO PRAZO', 'D'),
('AJUSTE DE PERDAS DE DEMAIS CRÉDITOS E VALORES A CURTO PRAZO', 'C'),
('INVESTIMENTOS E APLICAÇÕES TEMPORÁRIAS A CURTO PRAZO', 'D'),
('TÍTULOS E VALORES MOBILIÁRIOS', 'D'),
('AJUSTE DE PERDAS DE INVESTIMENTOS E APLICAÇÕES TEMPORÁRIAS', 'C'),
('ESTOQUES ', 'D'),
('MERCADORIAS PARA REVENDA', 'D'),
('PRODUTOS E SERVIÇOS ACABADOS', 'D'),
('PRODUTOS E SERVIÇOS EM ELABORAÇÃO', 'D'),
('MATÉRIAS-PRIMAS', 'D'),
('MATERIAIS EM TRÂNSITO', 'D'),
('ALMOXARIFADO', 'D'),
('ADIANTAMENTOS A FORNECEDORES', 'D'),
('AJUSTE DE PERDAS DE ESTOQUES', 'C'),
('AJUSTE DE PERDAS PARA REDUÇÃO AO VALOR DE MERCADO', 'C'),
('DESPESAS PAGAS ANTECIPADAMENTE', 'D'),
('PRÊMIOS DE SEGUROS A APROPRIAR', 'D'),
('DESPESAS FINANCEIRAS A APROPRIAR/A VENCER/ A TRANSCORRER', 'D'),
('ASSINATURAS E ANUIDADES A APROPRIAR', 'D'),
('ALUGUÉIS PAGOS A APROPRIAR', 'D'),
('TRIBUTOS PAGOS A APROPRIAR', 'D'),
('DEMAIS DESPESAS A APROPRIAR', 'D'),
('CRÉDITOS A LONGO PRAZO', 'D'),
('AJUSTE DE PERDAS DE CRÉDITOS A LONGO PRAZO', 'C'),
('CLIENTES (DUPLICATAS A RECEBER A LONGO PRAZO)', 'D'),
('AJUSTE DE PERDAS DE CLIENTES (LONGO PRAZO)', 'C'),
('EMPRÉSTIMOS E FINANCIAMENTOS CONCEDIDOS (LONGO PRAZO)', 'D'),
('AJUSTE DE PERDAS DE EMPRÉSTIMOS E FINANCIAMENTOS CONCEDIDOS(LONGO PRAZO)', 'C'),
('DEMAIS CRÉDITOS E VALORES A LONGO PRAZO', 'D'),
('PARTICIPAÇÕES PERMANENTES', 'D'),
('PARTICIPAÇÕES EM SOCIEDADES CONTROLADAS', 'D'),
('PARTICIPAÇÕES EM SOCIEDADES CONTROLADAS EM CONJUNTO', 'D'),
('PARTICIPAÇÕES EM SOCIEDADES COLIGADAS', 'D'),
('MAIS-VALIA SOBRE OS ATIVOS DAS INVESTIDAS', 'D'),
('ÁGIO SOBRE OS INVESTIMENTOS', 'D'),
('ADIANTAMENTO PARA FUTURO AUMENTO DE CAPITAL', 'D'),
('AMORTIZAÇÃO DE ÁGIO NA AQUISIÇÃO DE PARTICIPAÇÕES AVALIADAS PELO MEP', 'C'),
('PARTICIPAÇÕES AVALIADAS PELO MÉTODO DE CUSTO', 'D'),
('PROPRIEDADES PARA INVESTIMENTO', 'D'),
('DEMAIS INVESTIMENTOS PERMANENTES', 'D'),
('DEPRECIAÇÃO ACUMULADA DE INVESTIMENTOS', 'C'),
('REDUÇÃO AO VALOR RECUPERÁVEL DE INVESTIMENTOS', 'C'),
('BENS MÓVEIS', 'D'),
('MÓVEIS E UTENSÍLIOS', 'D'),
('VEÍCULOS', 'D'),
('BENS IMÓVEIS', 'D'),
('DEPRECIAÇÃO, EXAUSTÃO E AMORTIZAÇÃO ACUMULADAS', 'C'),
('REDUÇÃO AO VALOR RECUPERÁVEL DE IMOBILIZADO', 'C'),
('SOFTWARES', 'D'),
('MARCAS, DIREITOS E PATENTES INDUSTRIAIS', 'D'),
('DIREITOS AUTORAIS', 'D'), 
('DIREITOS SOBRE RECURSOS NATURAIS', 'D'),
('ADIANTAMENTO PARA TRANFERÊNCIA DE TECNOLOGIA', 'D'),
('DIREITO DE USO DE IMÓVEIS', 'D'),
('AMORTIZAÇÃO ACUMULADA', 'C'),
('REDUÇÃO AO VALOR RECUPERÁVEL DE INTANGÍVEL', 'C'),
('PESSOAL A PAGAR', 'C'),
('EMPRÉSTIMOS E FINANCIAMENTOS A CURTO PRAZO', 'C'),
('JUROS E ENCARGOS A PAGAR DE EMPRÉSTIMOS E FINANCIAMENTOS A CURTO PRAZO', 'C'),
('DUPLICATAS DESCONTADAS', 'C'),
('ENCARGOS FINANCEIROS (ATIVOS) A APROPRIAR/A VENCER/ A TRANSCORRER', 'D'),
('FORNECEDORES E CONTAS A PAGAR A CURTO PRAZO', 'C'),
('OBRIGAÇÕES FISCAIS A CURTO PRAZO', 'C'),
('IPI A RECOLHER', 'C'),
('IRPJ A RECOLHER', 'C'),
('PASSIVO FISCAL DIFERIDO', 'C'),
('CSSL A RECOLHER', 'C'),
('COFINS A RECOLHER', 'C'),
('PIS/PASEP A RECOLHER', 'C'),
('ICMS A RECOLHER', 'C'),
('ISS A RECOLHER', 'C'),
('IPTU/TLP A RECOLHER', 'C'),
('PROVISÕES A CURTO PRAZO', 'C'),
('PROVISÃO PARA RISCOS TRABALHISTAS A CURTO PRAZO', 'C'),
('PROVISÕES PARA RISCOS FISCAIS A CURTO PRAZO', 'C'),
('PROVISÃO PARA RISCOS CÍVEIS A CURTO PRAZO', 'C'),
('OUTRAS PROVISÕES A CURTO PRAZO', 'C'),
('ADIANTAMENTOS DE CLIENTES', 'C'),
('ARRENDAMENTO OPERACIONAL A PAGAR', 'C'),
('DEBÊNTURES E OUTROS TÍTULOS DE DIVIDA A CURTO PRAZO', 'C'),
('ÁGIO NA EMISSÃO DE DEBÊNTURES', 'C'),
('DESÁGIO NA EMISSÃO DE DEBÊNTURES', 'D'),
('CUSTO DA TRANSAÇÃO A AMORTIZAR', 'D'),
('DIVIDENDOS A PAGAR', 'C'),
('OUTRAS OBRIGAÇÕES A CURTO PRAZO', 'C'),
('OBRIGAÇÕES TRABALHISTAS, PREVIDENCIÁRIAS E ASSISTENCIAIS A PAGAR A LONGO PRAZO', 'C'),
('EMPRÉSTIMOS E FINANCIAMENTOS A LONGO PRAZO', 'C'),
('ENCARGOS FINANCEIROS A APROPRIAR', 'D'),
('FORNECEDORES A LONGO PRAZO', 'C'),
('OBRIGAÇÕES FISCAIS A LONGO PRAZO', 'C'),
('PASSIVO FISCAL DIFERIDO', 'C'),
('PROVISÕES A LONGO PRAZO', 'C'), 
('PROVISÃO PARA RISCOS TRABALHISTAS A LONGO PRAZO', 'C'),
('PROVISÃO PARA RISCOS FISCAIS A LONGO PRAZO', 'C'),
('PROVISÃO PARA RISCOS CÍVEIS A LONGO PRAZO', 'C'),
('OUTRAS PROVISÕES A LONGO PRAZO', 'C'),
('ADIANTAMENTOS DE CLIENTES A LONGO PRAZO', 'C'),
('DEBÊNTURES E OUTROS TÍTULOS DE DIVIDA A LONGO PRAZO', 'C'),
('ADIANTAMENTO PARA FUTURO AUMENTO DE CAPITAL', 'C'),
('OUTRAS OBRIGAÇÕES A LONGO PRAZO', 'C'),
('RECEITA DIFERIDA', 'C'),
('CUSTO DIFERIDO', 'D'),
('CAPITAL SOCIAL', 'C'),
('CAPITAL SUBSCRITO', 'C'),
('CAPITAL A REALIZAR/A INTEGRALIZAR', 'D'),
('GASTOS COM EMISSÃO DE AÇÕES', 'D'),
('ADIANTAMENTO PARA FUTURO AUMENTO DE CAPITAL', 'C'),
('RESERVAS DE CAPITAL', 'C'),
('ÁGIO NA EMISSÃO DE AÇÕES', 'C'),
('ALIENAÇÃO DE PARTES BENEFICIARIAS', 'C'),
('ALIENAÇÃO DE BÔNUS DE SUBSCRIÇÃO', 'C'),
('OPÇÕES OUTORGADAS RECONHECIDAS', 'C'),
('RESERVAS DE LUCROS', 'C'),
('RESERVA LEGAL', 'C'),
('RESERVAS ESTATUTÁRIAS', 'C'),
('RESERVA PARA CONTINGÊNCIAS', 'C'),
('RESERVA DE INCENTIVOS FISCAIS', 'C'),
('RESERVAS DE LUCROS PARA EXPANSÃO', 'C'),
('RESERVA DE LUCROS A REALIZAR', 'C'),
('RESERVA DE RETENÇÃO DE PRÊMIO NA EMISSÃO DE DEBÊNTURES', 'C'),
('LUCROS OU PREJUÍZOS ACUMULADOS(CREDOR)', 'C'),
('LUCROS OU PREJUÍZOS ACUMULADOS(DEVEDOR)', 'D'),
('LUCROS ACUMULADOS (A DESTINAR)', 'C'),
('PREJUÍZOS ACUMULADOS', 'D'),
('DIVIDENDO ADICIONAL PROPOSTO', 'C'),
('AÇÕES/COTAS EM TESOURARIA', 'D'),
('AJUSTES DE AVALIAÇÃO PATRIMONIAL(DÉBITO)', 'D'),
('AJUSTES DE AVALIAÇÃO PATRIMONIAL(CRÉDITO)', 'C'),
('AJUSTES DE EXERCICIOS ANTERIORES(DÉBITO)', 'D'),
('AJUSTES DE EXERCICIOS ANTERIORES(CRÉDITO)', 'C'),
('RECEITA LÍQUIDA', 'C'),
('RECEITA BRUTA DE VENDAS', 'C'),
('RECEITA DE VENDAS DE MERCADORIAS', 'C'),
('RECEITA DE SERVIÇOS PRESTADOS', 'C'),
('RECEITA DE VENDA DE PRODUTOS', 'C'),
('DEDUÇÕES DE VENDAS', 'D'),
('VENDAS CANCELADAS', 'D'),
('ABATIMENTOS', 'D'),
('DESCONTOS CONCEDIDOS', 'D'),
('IMPOSTOS SOBRE VENDAS', 'D'),
('ICMS SOBRE FATURAMENTO', 'D'),
('IPI SOBRE FATURAMENTO', 'D'),
('ISS SOBRE FATURAMENTO', 'D'),
('PIS SOBRE FATURAMENTO', 'D'),
('COFINS SOBRE FATURAMENTO', 'D'),
('LUCRO BRUTO OPERACIONAL', 'C'),
('RECEITAS FINANCEIRAS', 'C'),
('OUTRAS RECEITAS OPERACIONAIS', 'C'),
('RECEITAS NÃO OPERACIONAIS', 'C'),
('RECEITA DE ALIENAÇÃO DE BENS IMOBILIZADOS', 'C'),
('RECEITA COM ALIENAÇÃO DE INVESTIMENTOS', 'C'),
('OUTRAS RECEITAS NÃO OPERACIONAIS', 'C'),
('DESPESAS', 'D'),
('CUSTO DE MERCADORIAS VENDIDAS(CMV)', 'D'),
('CUSTO DE SERVIÇOS PRESTADOS', 'D'),
('CUSTO DE MATERIAIS APLICADOS', 'D'),
('CUSTO MÃO DE OBRA', 'D'),
('CUSTO DE ENCARGOS SOCIAIS', 'D'),
('CUSTO DE PODUTOS VENDIDOS', 'D'),
('CUSTOS DOS MATERIAIS', 'D'),
('CUSTO DE MÃO DE OBRA DIRETA', 'D'),
('DESPESAS OPERACIONAIS', 'D'),
('DESPESA COM VENDAS', 'D'),
('DESPESAS ADMINISTRATIVAS', 'D'),
('ORDENADOS, SALÁRIOS, GRATIFICAÇÕES E OUTRAS REMUNERAÇÕES À FUNCIONARIOS', 'D'),
('INSS- PREVIDÊNCIA SOCIAL', 'D'),
('FGTS', 'D'),
('VALE-TRANSPORTE', 'D'),
('DESPESAS GERAIS', 'D'),
('SERVIÇOS TOMADOS', 'D'),
('ENCARGOS DE DEPRECIAÇÃO E AMORTIZAÇÃO', 'D'),
('DESPESAS FINANCEIRAS', 'D')
;

-- Tabela ativo

insert into ativo(contas_id, grupo, subgrupo) values 
(1, 'ativo circulante', 'caixa e equivalentes'),
(2, 'ativo circulante', 'caixa e equivalentes'),
(3, 'ativo circulante', 'créditos a curto prazo'),
(4, 'ativo circulante', 'créditos a curto prazo'),
(5, 'ativo circulante', 'créditos a curto prazo'),
(6, 'ativo circulante', 'créditos a curto prazo'),
(7, 'ativo circulante', 'créditos a curto prazo'),
(8, 'ativo circulante', 'créditos a curto prazo'),
(9, 'ativo circulante', 'créditos a curto prazo'),
(10, 'ativo circulante', 'créditos a curto prazo'),
(11, 'ativo circulante', 'tributos a recuperar/compensar'),
(12, 'ativo circulante', 'tributos a recuperar/compensar'),
(13, 'ativo circulante', 'tributos a recuperar/compensar'),
(14, 'ativo circulante', 'tributos a recuperar/compensar'),
(15, 'ativo circulante', 'tributos a recuperar/compensar'),
(16, 'ativo circulante', 'tributos a recuperar/compensar'),
(17, 'ativo circulante', 'tributos a recuperar/compensar'),
(18, 'ativo circulante', 'outros créditos a receber e valores a curto prazo'),
(19, 'ativo circulante', 'outros créditos a receber e valores a curto prazo'),
(20, 'ativo circulante', 'outros créditos a receber e valores a curto prazo'),
(21, 'ativo circulante', 'outros créditos a receber e valores a curto prazo'),
(22, 'ativo circulante', 'outros créditos a receber e valores a curto prazo'),
(23, 'ativo circulante', 'outros créditos a receber e valores a curto prazo'),
(24, 'ativo circulante', 'outros créditos a receber e valores a curto prazo'),
(25, 'ativo circulante', 'investimentos e aplicações temporárias a curto prazo'),
(26, 'ativo circulante', 'investimentos e aplicações temporárias a curto prazo'),
(27, 'ativo circulante', 'investimentos e aplicações temporárias a curto prazo'),
(28, 'ativo circulante', 'estoques'),
(29, 'ativo circulante', 'estoques'),
(30, 'ativo circulante', 'estoques'),
(31, 'ativo circulante', 'estoques'),
(32, 'ativo circulante', 'estoques'),
(33, 'ativo circulante', 'estoques'),
(34, 'ativo circulante', 'estoques'),
(35, 'ativo circulante', 'estoques'),
(36, 'ativo circulante', 'estoques'),
(37, 'ativo circulante', 'estoques'),
(38, 'ativo circulante', 'despesas pagas antecipadamente'),
(39, 'ativo circulante', 'despesas pagas antecipadamente'),
(40, 'ativo circulante', 'despesas pagas antecipadamente'),
(41, 'ativo circulante', 'despesas pagas antecipadamente'),
(42, 'ativo circulante', 'despesas pagas antecipadamente'),
(43, 'ativo circulante', 'despesas pagas antecipadamente'),
(44, 'ativo circulante', 'despesas pagas antecipadamente'),
(45, 'ativo não circulante', 'ativo realizável a longo prazo'),
(46, 'ativo não circulante', 'ativo realizável a longo prazo'),
(47, 'ativo não circulante', 'ativo realizável a longo prazo'),
(48, 'ativo não circulante', 'ativo realizável a longo prazo'),
(49, 'ativo não circulante', 'ativo realizável a longo prazo'),
(50, 'ativo não circulante', 'ativo realizável a longo prazo'),
(51, 'ativo não circulante', 'ativo realizável a longo prazo'),
(52, 'ativo não circulante', 'investimentos'),
(53, 'ativo não circulante', 'investimentos'),
(54, 'ativo não circulante', 'investimentos'),
(55, 'ativo não circulante', 'investimentos'),
(56, 'ativo não circulante', 'investimentos'),
(57, 'ativo não circulante', 'investimentos'),
(58, 'ativo não circulante', 'investimentos'),
(59, 'ativo não circulante', 'investimentos'),
(60, 'ativo não circulante', 'investimentos'),
(61, 'ativo não circulante', 'investimentos'),
(62, 'ativo não circulante', 'investimentos'),
(63, 'ativo não circulante', 'investimentos'),
(64, 'ativo não circulante', 'investimentos'),
(65, 'ativo não circulante', 'imobilizado'),
(66, 'ativo não circulante', 'imobilizado'),
(67, 'ativo não circulante', 'imobilizado'),
(68, 'ativo não circulante', 'imobilizado'),
(69, 'ativo não circulante', 'imobilizado'),
(70, 'ativo não circulante', 'imobilizado'),
(71, 'ativo não circulante', 'intangível'),
(72, 'ativo não circulante', 'intangível'),
(73, 'ativo não circulante', 'intangível'),
(74, 'ativo não circulante', 'intangível'),
(75, 'ativo não circulante', 'intangível'),
(76, 'ativo não circulante', 'intangível'),
(77, 'ativo não circulante', 'intangível'),
(78, 'ativo não circulante', 'intangível')
;

-- Tabela passivo

insert into passivo(contas_id, grupo) values 
(79, 'passivo circulante'),
(80, 'passivo circulante'),
(81, 'passivo circulante'),
(82, 'passivo circulante'),
(83, 'passivo circulante'),
(84, 'passivo circulante'),
(85, 'passivo circulante'),
(86, 'passivo circulante'),
(87, 'passivo circulante'),
(88, 'passivo circulante'),
(89, 'passivo circulante'),
(90, 'passivo circulante'),
(91, 'passivo circulante'),
(92, 'passivo circulante'),
(93, 'passivo circulante'),
(94, 'passivo circulante'),
(95, 'passivo circulante'),
(96, 'passivo circulante'),
(97, 'passivo circulante'),
(98, 'passivo circulante'),
(99, 'passivo circulante'),
(100, 'passivo circulante'),
(101, 'passivo circulante'),
(102, 'passivo circulante'),
(103, 'passivo circulante'),
(104, 'passivo circulante'),
(105, 'passivo circulante'),
(106, 'passivo circulante'),
(107, 'passivo circulante'),
(108, 'passivo não circulante'),
(109, 'passivo não circulante'),
(110, 'passivo não circulante'),
(111, 'passivo não circulante'),
(112, 'passivo não circulante'),
(113, 'passivo não circulante'),
(114, 'passivo não circulante'),
(115, 'passivo não circulante'),
(116, 'passivo não circulante'),
(117, 'passivo não circulante'),
(118, 'passivo não circulante'),
(119, 'passivo não circulante'),
(120, 'passivo não circulante'),
(121, 'passivo não circulante'),
(122, 'passivo não circulante'),
(123, 'passivo não circulante'),
(124, 'passivo não circulante')
;

-- Tabela patrimonio_liquido
insert into patrimonio_liquido(contas_id, grupo) values
(125, 'capital social'),
(126, 'capital social'),
(127, 'capital social'),
(128, 'capital social'),
(129, 'reservas de capital'),
(130, 'reservas de capital'),
(131, 'reservas de capital'),
(132, 'reservas de capital'),
(133, 'reservas de lucros'),
(134, 'reservas de lucros'),
(135, 'reservas de lucros'),
(136, 'reservas de lucros'),
(137, 'reservas de lucros'),
(138, 'reservas de lucros'),
(139, 'reservas de lucros'),
(140, 'reservas de lucros'),
(141, null),
(142, null),
(143, null),
(144, null),
(145, null),
(146, null),
(147, null),
(148, null),
(149, null), 
(150, null),
(151, null),
(152, null)
;

-- Tabela contas_de_resultado

insert into contas_de_resultado(contas_id, grupo) values
(153, 'receitas'),
(154, 'receitas'),
(155, 'receitas'),
(156, 'receitas'),
(157, 'receitas'),
(158, 'receitas'),
(159, 'receitas'),
(160, 'receitas'),
(161, 'receitas'),
(162, 'receitas'),
(163, 'receitas'),
(164, 'receitas'),
(165, 'receitas'),
(166, 'receitas'),
(167, 'receitas'),
(168, 'receitas'),
(169, 'receitas'),
(170, 'receitas'),
(171, 'receitas'),
(172, 'receitas'),
(173, 'despesas'),
(174, 'despesas'),
(175, 'despesas'),
(176, 'despesas'),
(177, 'despesas'),
(178, 'despesas'),
(179, 'despesas'),
(180, 'despesas'),
(181, 'despesas'),
(182, 'despesas'),
(183, 'despesas'),
(184, 'despesas'),
(185, 'despesas'),
(186, 'despesas'),
(187, 'despesas'),
(188, 'despesas'),
(189, 'despesas'),
(190, 'despesas'),
(191, 'despesas'),
(192, 'despesas')
;